#pragma config(Sensor, in1,    potMogo,        sensorPotentiometer)
#pragma config(Sensor, in2,    potLeftLift,    sensorPotentiometer)
#pragma config(Sensor, in3,    potRightLift,   sensorPotentiometer)
#pragma config(Sensor, in4,    potFourBar,     sensorPotentiometer)
#pragma config(Sensor, in5,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  encDrive,       sensorQuadEncoder)
#pragma config(Motor,  port1,           driveLeftBack, tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           driveRightBack, tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           liftLeft,      tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           fourBarLeft,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           fourBarRight,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           roller,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           liftRight,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           driveLeftFront, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           driveRightFront, tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          mogo,          tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)
#include "Vex_Competition_Includes.c"

#include "function.h";

//float ticsPerDegree = (37870/36000);

int autonomousChoice = 0;
bool auton = false;

task doubleCheck()
{
	while(bIfiRobotDisabled && !bIfiAutonomousMode)
	{
		delay(1);
	}
	auton = true;
}

void pre_auton()
{
	startTask(doubleCheck);
	bLCDBacklight = true;
	// bStopTasksBetweenModes = true;
	clearLCD();
	while(!auton)
	{
		centerLine(0,autonomousMenu[autonomousChoice]);
		centerLine(1, "Auton | Settings");

		//	waitForPress();

		if(nLCDButtons == leftButton)
		{
			waitForRelease();
			autonomousChoice = autonChooser();
		}

		else if(nLCDButtons == rightButton)
		{
			waitForRelease();
			settings();
		}

		else if(nLCDButtons == centerButton)
		{
			waitForRelease();
			preAutonBattery();
		}

	}
}


/////////////////////////////////////////////////////////////////////////////////////////
//                                 Autonomous Task
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	//Clear LCD
	bLCDBacklight = false;
	clearLCD();

	centerLine(0,autonomousMenu[autonomousChoice]);
	centerLine(1,"Target>Error");
skills();
	switch(autonomousChoice){
	case 0:			  break;
	case 1:	      break;
	case 2:       break;
	case 3:       break;
	case 4:       break;
	case 5:       break;
	case 6:       break;
	case 7:       break;
	case 8:       break;
	case 9:       break;
	case 10:      break;
	case 11:      break;

	default:
		displayLCDCenteredString(0, "This should");
		displayLCDCenteredString(1, "never happen");
		auton = true;
		wait1Msec(15000);
		break;
	}
}

/////////////////////////////////////////////////////////////////////////////////////////
//                                 User Control Task
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{

	bLCDBacklight = false;
	clearLCD();
	startTask(batteryLCD);
	powRoller(80);
	while (true)
	{

		driverControl();

		wait1Msec(5);
	}
}
